services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_source_base
    # restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs-app
    # restart: always
    # env_file: ".env"
    # environment:
    #   - NODE_ENV=production
    #   - APP_NAME=APP_NAME
    #   - PORT=8000
    #   - DB_HOST=postgres-db
    #   - DB_PORT=5432
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=postgres
    #   - DB_NAME=nestjs_source_base
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - postgres-db

  migration:
    # run migration to create table in db
    build: .
    container_name: nestjs-migration
    depends_on:
      - postgres-db
    command: ["npm", "run", "migration:run"]


volumes:
  pgdata:
